# Generated by Django 2.2.3 on 2020-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydjobs',
            name='phone',
            field=models.BigIntegerField(default=9096273788),
            preserve_default=False,
        ),
    ]
